# 工作流名称
name: Build and Download Image Artifact

# 只保留手动触发，并让用户选择平台和功能
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: '请选择要构建的镜像平台'
        required: true
        default: 'linux/amd64'
        options: 
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      enable_forwarding:
        type: choice
        description: '构建时是否内置“开启网络转发”功能?'
        required: true
        default: 'true'
        options:
        - 'true'
        - 'false'

jobs:
  build-and-download:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare dynamic names and variables
        id: vars
        run: |
          # 1. 处理平台名称，使其更简洁 (例如 'linux/arm/v7' -> 'armv7')
          INPUT_PLATFORM="${{ github.event.inputs.platform }}"
          SIMPLE_PLATFORM=$(echo ${INPUT_PLATFORM} | sed 's#linux/##' | sed 's#/v##')
          echo "SIMPLE_PLATFORM=${SIMPLE_PLATFORM}" >> $GITHUB_OUTPUT
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: local/gateway-${{ steps.vars.outputs.SIMPLE_PLATFORM }}
          tags: type=raw,value=latest

      - name: Build image and export to tarball
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ github.event.inputs.platform }}
          # 将用户选择的转发状态作为构建参数传递给 Dockerfile
          build-args: |
            ENABLE_FORWARDING=${{ github.event.inputs.enable_forwarding }}
          push: false
          outputs: type=docker,dest=/tmp/image.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          # 使用体现功能组合的新命名规则
          name: gateway-zerotier+singbox-${{ steps.vars.outputs.SIMPLE_PLATFORM }}
          path: /tmp/image.tar
          retention-days: 7
